export interface SmeIpoData {
    id: string;
    image: string;
    title: string;
    offer_date: string;
    price: string;
    lot_size: string;
    gmp: string;
    gain: string;
    label: string;
    open_date: string;
    close_date: string;
    offer_price: string;
    subscription: string;
    ipo_size: string;
    face_value: string;
    retail_quota: string;
    amount: string;
    allotment_date: string;
    listing_date: string;
    listing_group: string;
    lead_manager: string;
    register: string;
    eps_per_ipo: string;
    company_about: string;
    company_promoter: string;
    issue_objective: string;
    disclaimer: string;
    company_financial: Array<any>;
    drhp: string;
    rhp: string;
    apply_now:string;
    allotment_link:string;
}
